agent:
  name: bytetrack_agent
  description: Agent to perform ByteTrack inference using Ultralytics YOLO model as detector (real-time).

templates:
  - template_name: InputTemplate
    class_name: InputTemplate
    attributes: {}

  - template_name: UltralyticsPredict
    class_name: UltralyticsPredict
    template_input: InputTemplate
    attributes:
      model_class: YOLO
      model: yolo11n.pt
      task: detect
      prediction_params:
        conf: 0.7
        iou: 0.8

  - template_name: ByteTrack
    class_name: ByteTrack
    template_input: UltralyticsPredict
    attributes:
      track_activation_threshold: 0.2
      frame_rate: 30

  - template_name: BBoxDrawer
    class_name: BBoxDrawer
    template_input: ByteTrack
    attributes:
      overwrite: true
      draw_classification_label: false
      randomized_color: false