agent:
  name: cotracker_agent
  description: >
    "Agent to load video from local dir, perform CoTrackerOffline inference
    and store visualization results in destination path."

templates:
  - template_name: InputTemplate
    class_name: InputTemplate
    attributes: {}

  - template_name : VideoReaderCV2
    class_name: VideoReaderCV2
    template_input: InputTemplate
    attributes:
      video_file_path : "artifacts/bear.mp4"
      batch_size: -1

  - template_name: CoTrackerOffline
    class_name: CoTrackerOffline
    template_input: VideoReaderCV2
    attributes:
      model_variant: baseline
      device: cuda
      grid_size: 15

  - template_name: CoTrackerVisualizer
    class_name: CoTrackerVisualizer
    template_input: CoTrackerOffline
    attributes:
      device : cuda
      pad_value: 120
      linewidth: 3
      overwrite: true
      generic_key_field: CoTrackerOffline

  - template_name: VideoWriterCV2
    class_name: VideoWriterCV2
    template_input: CoTrackerVisualizer
    attributes:
      destination_path: "artifacts/result.mp4"
      height: -1
      width: -1
      fps: 30